<?php

/**
 * Implementation of hook_menu().
 */
function oa_sandbox_menu(){
  $items = array();
  $items['admin/openatrium/sandbox'] = array(
    'title' => 'Sandbox Mode',
    'description' => 'Toggle Sandbox mode',
    'access arguments' => array('toggle sandbox mode'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('oa_sandbox_settings_form'),
    'type' => MENU_NORMAL_ITEM
  );
  return $items;
}

/**
 * Implementation of hook_permission()
 */
function oa_sandbox_permission() {
  return array(
    'toggle sandbox mode' => array(
      'title' => t('Toggle Sandbox mode'),
      'description' => t('Turn Sandbox mode on or off'),
    ),
  );
}

/**
 * Form builder for the settings form.
 */
function oa_sandbox_settings_form($form, &$form_state) {
  $form = array();
  $form['help'] = array(
    '#markup' => '<p>' . t('If sandbox mode is on, any content you add or edit will be reverted/destroyed when you turn sandbox mode back off. It\'s a chance to play with your site and edit things as you wish without worrying about any lasting repercussions.') . '</p>',
  );
  $form['toggle'] = array(
    '#type' => 'checkbox',
    '#default_value' => variable_get('oa_sandbox_mode', 0),
    '#title' => t('Activate sandbox mode?'),
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save')
  );
  return $form;
}

/**
 * Submit handler for the settings form.
 */
function oa_sandbox_settings_form_submit($form, $form_state){
  $was_active = variable_get('oa_sandbox_mode', 0);
  $is_active = $form_state['values']['toggle'];
  variable_set('oa_sandbox_mode', $is_active);
  drupal_set_message('The confirmation options have been saved.');
}

/**
 * Implementation of hook_page_build().
 * Show an indicator if sandbox mode is currently on.
 */
function oa_sandbox_page_build(&$page) {
  if (variable_get('oa_sandbox_mode', 0) && user_access('toggle sandbox mode')) {
    $page['page_top']['oa_sandbox_indicator'] = array(
      '#theme' => 'oa_sandbox_indicator',
    );
    drupal_add_css(drupal_get_path('module', 'oa_sandbox') . '/oa_sandbox.css');
  }
}

/**
 * Implementation of hook_theme().
 */
function oa_sandbox_theme($existing, $type, $theme, $path) {
  return array(
    'oa_sandbox_indicator' => array(),
  );
}

/**
 * Theme function for the indicator bar.
 */
function theme_oa_sandbox_indicator($variables) {
  $output = array(
    '#type' => 'container',
    '#attributes' => array(
      'id' => 'oa-sandbox-indicator',
    ),
    'name' => array(
      '#theme' => 'html_tag',
      '#tag' => 'h3',
      '#value' => l(t('Sandbox Mode'), 'admin/openatrium/sandbox', array('attributes' => array('title' => 'Click this to toggle sandbox mode.'))),
    ),
  );
  return drupal_render($output);
}
